In [1]:
import numpy as np

Casting normal list to array

1-D array

In [ ]:
my_list1 = [1,2,3]

In [6]:
np.array(my_list1)

array([1, 2, 3])

2-D array

In [ ]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Creating a array using 'arange' function

In [21]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'arange(start,stop,steps)'

In [24]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Creating Zeros arrays 1-D and 2-D

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
#Pass a tuple (rows,columns)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

'linspace(start,stop,number of points you want between range)'
Linspace distribute number 10 evenly space number form range 0 to 5,its 1-D array

In [26]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

'eye' will generate a identity matrix,number of rows = number of columns 

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

'rand' func will generate 1-D array of 'n' elements,number is uniformly distributed from 0 to 1

In [28]:
np.random.rand(5)

array([0.69310124, 0.41356596, 0.90130606, 0.56735632, 0.63405101])

In [29]:
np.random.rand(3,4)

array([[0.37165679, 0.71683384, 0.30474096, 0.00369461],
       [0.61200194, 0.10148622, 0.05986892, 0.98416166],
       [0.19465241, 0.65470144, 0.42886223, 0.42063764]])

'randn' will return a sample or many samples from the standard Normal or Gaussian Distribution

In [30]:
np.random.randn(3)

array([1.40404921, 0.26180727, 1.83601886])

In [31]:
np.random.randn(3,2)

array([[-1.26891447,  0.92540869],
       [-0.77363598,  0.92898876],
       [-0.50697264, -0.79705864]])

'randint(start,stop{not including},count of number you wwant)' it will return random integers from a low to high number

In [37]:
np.random.randint(0,50)

41

In [36]:
np.random.randint(1,100,10)

array([72, 40, 37, 89, 44, 34, 71, 44, 73, 33])

'reshape(rows,columns)' according to the data it will arrange the data in particular row and column

In [33]:
arr = np.arange(20)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
arr2 = np.random.randint(0,100,10)

In [40]:
arr2

array([19, 88, 38, 76, 25, 55, 37, 98, 57, 96])

In [41]:
arr2.max()

98

In [42]:
arr2.min()

19

In [43]:
arr2.sort()

In [44]:
arr2

array([19, 25, 37, 38, 55, 57, 76, 88, 96, 98])

'argmax' will return index value of maximum value,'argmin' will return index value of minimum value

In [45]:
arr2.argmax()

9

In [47]:
arr2.argmin()

0